# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8056363c7cfc4fd9e5549706140b5c5173d687aa463e48731caef76a9ceb5a4d164109cced97bbbd9aded668eeb67b7a1331aac9b8b87467af14da212899daf

test:
  secret_key_base: 927167fcd1778b3d132625a9d44665798cea251f585b50a5d53d3f4b4efce654eb443e220442983f77e71127749d59e3103933813c26d5970de425af6b7329cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
